version: "3"
services:
  recordings-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "posts"
    ports:
      - "5432:5432"
  recordings-service:
    build: ./server
    depends_on:
      - recordings-db
    ports:
      - "4000:4000"
  web-app:
    build: ./client
    ports:
      - "5000:5000"
