version: "3"

volumes:
  static_site:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "recordings"
    ports:
      - "5432:5432"

  service:
    build: ./server
    depends_on:
      - db
    ports:
      - "4000:3000"
    volumes:
      - static_site:/app/public:ro

  website:
    build: ./client
    volumes:
      - static_site:/app/build:rw
